package Objects;

public class Object_Ordbok_Pynting extends Object_Ordbok_Old {

	public void FyllOrdbok() {
		int X = 0;
		
		X++;
		Ord[X].Ordet = "accessories";
		Ord[X].RelationValue = 15;
		Ord[X].SaveValue = 10;
		X++;
		Ord[X].Ordet = "jewelry";
		Ord[X].RelationValue = 20;
		Ord[X].SaveValue = 10;
		X++;
		Ord[X].Ordet = "cosmetics";
		Ord[X].RelationValue = 5;
		Ord[X].SaveValue = 5;
		X++;
		Ord[X].Ordet = "piercings";
		Ord[X].RelationValue = 20;
		Ord[X].SaveValue = 10;
		X++;
		Ord[X].Ordet = "lingerie";
		Ord[X].RelationValue = 10;
		Ord[X].SaveValue = 5;
		X++;
		Ord[X].Ordet = "buy";
		Ord[X].RelationValue = 3;
		Ord[X].SaveValue = 1;
		X++;
		Ord[X].Ordet = "shop";
		Ord[X].RelationValue = 3;
		Ord[X].SaveValue = 1;
		X++;
		Ord[X].Ordet = "order";
		Ord[X].RelationValue = 3;
		Ord[X].SaveValue = 1;
		X++;
		Ord[X].Ordet = "fashion";
		Ord[X].RelationValue = 4;
		Ord[X].SaveValue = 1;
		X++;
		Ord[X].Ordet = "wholesale";
		Ord[X].RelationValue = 20;
		Ord[X].SaveValue = 10;
		X++;
		Ord[X].Ordet = "dropship";
		Ord[X].RelationValue = 20;
		Ord[X].SaveValue = 10;
		X++;
		Ord[X].Ordet = "import";
		Ord[X].RelationValue = 10;
		Ord[X].SaveValue = 2;
		X++;
		Ord[X].Ordet = "international";
		Ord[X].RelationValue = 5;
		Ord[X].SaveValue = 3;
		X++;
		Ord[X].Ordet = "clearance";
		Ord[X].RelationValue = 10;
		Ord[X].SaveValue = 2;
		X++;
		Ord[X].Ordet = "overstock";
		Ord[X].RelationValue = 10;
		Ord[X].SaveValue = 2;
		X++;
		Ord[X].Ordet = "swarovski";
		Ord[X].RelationValue = 10;
		Ord[X].SaveValue = 10;
		X++;
		Ord[X].Ordet = "stainless";
		Ord[X].RelationValue = 5;
		Ord[X].SaveValue = 1;
		X++;
		Ord[X].Ordet = "stainless";
		Ord[X].RelationValue = 10;
		Ord[X].SaveValue = 1;
		
		
		X++;
		Ord[X].Ordet = "google";
		Ord[X].RelationValue = 0;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "wiki";
		Ord[X].RelationValue = 0;
		Ord[X].SaveValue = -20;
		
		X++;
		Ord[X].Ordet = "support";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "roadmap";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "advertise";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "college";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "school";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "tattoo";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = 5;
		X++;
		Ord[X].Ordet = "GB2312";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -30;
		X++;
		Ord[X].Ordet = "ebay";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "amazon";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "sex";
		Ord[X].RelationValue = -11;
		Ord[X].SaveValue = 0;
		X++;
		Ord[X].Ordet = "article";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "comic";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "collection";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "about us";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "contact";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "exhibition";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "litera";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "news";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -10;
		X++;
		Ord[X].Ordet = ".no/";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "shopping";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "gift card";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "wish list";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "forum";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -10;
		X++;
		Ord[X].Ordet = "watches";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "promotion";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "toys";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "fishing";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "usb";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "baby";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "search";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "camera";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "mask";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "wedding";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "home";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "garden";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -10;
		X++;
		Ord[X].Ordet = "office";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "ball";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "athletic";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "club";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "travel";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "movie";
		Ord[X].RelationValue = -1;
		Ord[X].SaveValue = -2;
		X++;
		Ord[X].Ordet = "privacy";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "affiliate";
		Ord[X].RelationValue = -2;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "auto";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "food";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -5;
		X++;
		Ord[X].Ordet = "audio";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "health";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "disclaimer";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "computer";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "customer";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "login";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "account";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "artist";
		Ord[X].RelationValue = -10;
		Ord[X].SaveValue = -10;
		X++;
		Ord[X].Ordet = "paint";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "brush";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "device";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "recycle";
		Ord[X].RelationValue = -20;
		Ord[X].SaveValue = -20;
		X++;
		Ord[X].Ordet = "help";
		Ord[X].RelationValue = -5;
		Ord[X].SaveValue = -1;
		
		
		X++;
		Ord[X].Ordet = "Your browser sent a request that this server could not understand.";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "We apologize for the inconvenience. Please contact the webmaster/ tech support immediately to have them rectify this.";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "You don't have permission to access / on this server.";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "The requested URL / was not found on this server. That’s all we know.";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "Make sure you did not mis-type the URL.";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "Page Not Responding";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		X++;
		Ord[X].Ordet = "This listing () has been removed, or this item is not available.";
		Ord[X].RelationValue = -30;
		Ord[X].SaveValue = -1;
		
		
	}

}
