package Objects;

public class Object_Ordbok_Caboose extends Object_Ordbok_Old {

	public void FyllOrdbok() {
		int X = 0;
		
		Ord[X].Ordet = "hans caboose";
		Ord[X].Value = 30;
		X++;
		Ord[X].Ordet = "hanscaboose";
		Ord[X].Value = 30;
		X++;
		Ord[X].Ordet = "hansleonard";
		Ord[X].Value = 20;
		X++;
		Ord[X].Ordet = "hans-leonard kjenes";
		Ord[X].Value = 30;
		X++;
		Ord[X].Ordet = "hans leonard kjenes";
		Ord[X].Value = 30;
		X++;
		Ord[X].Ordet = "hans-leonard";
		Ord[X].Value = 10;
		X++;
		Ord[X].Ordet = "Ammerudveien 71, 0958 Oslo";
		Ord[X].Value = 15;
		X++;
		Ord[X].Ordet = "Ammerudveien 71 0958 Oslo";
		Ord[X].Value = 15;
		X++;
		Ord[X].Ordet = "Ammerudveien 71";
		Ord[X].Value = 15;
		X++;
		Ord[X].Ordet = "warhammer";
		Ord[X].Value = 5;
		X++;
		Ord[X].Ordet = "2d6";
		Ord[X].Value = 5;
		X++;
		Ord[X].Ordet = "halo";
		Ord[X].Value = 5;
		X++;
		Ord[X].Ordet = "heavy metal";
		Ord[X].Value = 5;
		X++;
		Ord[X].Ordet = "464 14 049";
		Ord[X].Value = 10;
		X++;
		Ord[X].Ordet = "46414049";
		Ord[X].Value = 10;
		X++;
		Ord[X].Ordet = "xbox";
		Ord[X].Value = 5;
		X++;
		Ord[X].Ordet = "19 år";
		Ord[X].Value = 1;
		X++;
		Ord[X].Ordet = "innebandy";
		Ord[X].Value = 5;
		X++;
		Ord[X].Ordet = "sveiva";
		Ord[X].Value = 1;
		X++;
		Ord[X].Ordet = "målløs";
		Ord[X].Value = 1;
		X++;
		Ord[X].Ordet = "oslo";
		Ord[X].Value = 1;
		X++;
		Ord[X].Ordet = "molde";
		Ord[X].Value = 1;
		X++;

		X++;
		Ord[X].Ordet = "innenriks";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "utenriks";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "næringsliv";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "lov og rett";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "finans";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "nyheter";
		Ord[X].Value = -1;
		X++;
		Ord[X].Ordet = "bil";
		Ord[X].Value = -1;
		X++;
		Ord[X].Ordet = "olje";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "politikk";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "eiendom";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "Your browser sent a request that this server could not understand.";
		Ord[X].Value = -999;
		X++;
		Ord[X].Ordet = "We apologize for the inconvenience. Please contact the webmaster/ tech support immediately to have them rectify this.";
		Ord[X].Value = -999;
		X++;
		Ord[X].Ordet = "You don't have permission to access / on this server.";
		Ord[X].Value = -999;
		X++;
		Ord[X].Ordet = "The requested URL / was not found on this server. That’s all we know.";
		Ord[X].Value = -999;
		X++;
		Ord[X].Ordet = "Make sure you did not mis-type the URL.";
		Ord[X].Value = -999;
		
		
	}
}
